### ISSUE TITLE
Initial Verification

### ISSUE THREAD

**Issue by rmcewan** [nlpie/nlp-adapt#1] opened 2018-01-18 18:29 UTC
Using existing VM, verify that the following pieces work as intended with a small set of mimic notes.

Components include:

- [x] biomedicus
- [x] nlp-tab
- [x] amicus 
- [x] elastic
- [x] total pipeline

**Comment by rfinz** [comment] 2018-01-30 18:22
Each piece seems to work on its own, but there seems to be a document in the mimic set that I have that's breaking processing on Biomedicus 1.8.1 right now. Tracking down the document, but it we will want a script that flags problematic files for the institutions.

**Comment by rmcewan** [comment] 2018-01-31 21:30
Could look into isValidXmlFile method in http://uima.apache.org/d/uima-as-2.4.0/api/org/apache/uima/pear/util/XMLUtil.html#isValidXmlFile(java.io.File) for use in the script.

**Comment by rfinz** [comment] 2018-02-02 18:30
@GregSilverman is helping track down the file that Biomedicus is breaking on and @benknoll-umn is working on a hotfix to make that easier. I've tested Amicus now with output from cTAKES, but I can't call this Issue complete until I've seen it work with multiple type systems.

**Comment by GregSilverman** [comment] 2018-02-02 19:28
On a similar note, it would be nice to know which files were processed before an error gets thrown. Could this be logged?

**Comment by GregSilverman** [comment] 2018-02-02 21:39
@benknoll-umn @rfinz, I Found the following problematic files in the mimic data set running release 1.8.2:
732645.txt
911139.txt
741251.txt
712849.txt

I'm not going to go through and try and find all the exceptions at this time, since I am now about 1/10th of the way through reading these in. I'll examine the files. 

The error I am getting is the same for each (:

2018-02-02 15:33:28,070 ERROR [[Procesing Pipeline#1 Thread]::] DocumentProcessorRunner (DocumentProcessorRunner.java:105) - Processing failed on document: 712849
2018-02-02 15:33:28,070 ERROR [[Procesing Pipeline#1 Thread]::] DocumentProcessorUimaAdapter (DocumentProcessorUimaAdapter.java:115) - error while processing document
2018-02-02 15:33:28,070 ERROR [[Procesing Pipeline#1 Thread]::] PrimitiveAnalysisEngine_impl (PrimitiveAnalysisEngine_impl.java:417) - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:116) ~[biomedicus-uima-1.8.2.jar:?]

...

2018-02-02 15:33:28,082 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2345) - The container Default BioMedICUS Pipeline returned the following error message: null (Thread Name: [Procesing Pipeline#1 Thread]::)
2018-02-02 15:33:28,083 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2498) - Thread: [Procesing Pipeline#1 Thread]::, message: null
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:116) ~[biomedicus-uima-1.8.2.jar:?]
	at org.apache.uima.analysis_component.CasAnnotator_ImplBase.process(CasAnnotator_ImplBase.java:56) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:893) [uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575) [uimaj-cpe-2.8.1.jar:2.8.1]
Caused by: edu.umn.biomedicus.exc.BiomedicusException: java.lang.NullPointerException: numberType
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.processDocument(DocumentProcessorRunner.java:106) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:113) ~[biomedicus-uima-1.8.2.jar:?]
	... 10 more
Caused by: java.lang.NullPointerException: numberType
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228) ~[guava-19.0.jar:?]
	at edu.umn.biomedicus.measures.ImmutableNumber$Builder.numberType(ImmutableNumber.java:235) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.measures.NumberRecognizer.labelSeq(NumberRecognizer.java:126) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.measures.NumberRecognizer.extract(NumberRecognizer.java:101) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.measures.NumberRecognizer.process(NumberRecognizer.java:76) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.lambda$processDocument$0(DocumentProcessorRunner.java:101) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.framework.BiomedicusScopes$Context.call(BiomedicusScopes.java:134) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.processDocument(DocumentProcessorRunner.java:100) ~[biomedicus-core-1.8.2.jar:?]
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:113) ~[biomedicus-uima-1.8.2.jar:?]
	... 10 more
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:116)
	at org.apache.uima.analysis_component.CasAnnotator_ImplBase.process(CasAnnotator_ImplBase.java:56)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:893)
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575)
Caused by: edu.umn.biomedicus.exc.BiomedicusException: java.lang.NullPointerException: numberType
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.processDocument(DocumentProcessorRunner.java:106)
	at edu.umn.biomedicus.uima.adapter.DocumentProcessorUimaAdapter.process(DocumentProcessorUimaAdapter.java:113)
	... 10 more
Caused by: java.lang.NullPointerException: numberType
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at edu.umn.biomedicus.measures.ImmutableNumber$Builder.numberType(ImmutableNumber.java:235)
	at edu.umn.biomedicus.measures.NumberRecognizer.labelSeq(NumberRecognizer.java:126)
	at edu.umn.biomedicus.measures.NumberRecognizer.extract(NumberRecognizer.java:101)
	at edu.umn.biomedicus.measures.NumberRecognizer.process(NumberRecognizer.java:76)
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.lambda$processDocument$0(DocumentProcessorRunner.java:101)
	at edu.umn.biomedicus.framework.BiomedicusScopes$Context.call(BiomedicusScopes.java:134)
	at edu.umn.biomedicus.framework.DocumentProcessorRunner.processDocument(DocumentProcessorRunner.java:100)
	... 11 more
2018-02-02 15:34:08,015 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingContainer_Impl (ProcessingContainer_Impl.java:786) - The CPM stopped because the configured error threshold 0 was exceeded. (Thread Name: [Procesing Pipeline#1 Thread]::) Component Name: Default BioMedICUS Pipeline
2018-02-02 15:34:08,017 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2345) - The CPM is terminating. The current component is Default BioMedICUS Pipeline. (Thread Name: [Procesing Pipeline#1 Thread]::)
2018-02-02 15:34:08,017 WARN  [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2345) - The CPM cannot be stopped by force. The current container is Default BioMedICUS Pipeline. (Thread Name: [Procesing Pipeline#1 Thread]::) Reason: The CAS processor Default BioMedICUS Pipeline is configured to stop the CPM when excessive errors are encountered.  (Thread Name: [Procesing Pipeline#1 Thread]::)
2018-02-02 15:34:08,018 INFO  [[CollectionReader Thread]::] FilesInDirectoryReader (FilesInDirectoryReader.java:179) - Reading file: 714545.txt
2018-02-02 15:34:08,018 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2498) - Thread: [Procesing Pipeline#1 Thread]::, message:
org.apache.uima.collection.base_cpm.AbortCPMException:
	at org.apache.uima.collection.impl.cpm.container.ProcessingContainer_Impl.incrementCasProcessorErrors(ProcessingContainer_Impl.java:795) ~[uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:1037) [uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575) [uimaj-cpe-2.8.1.jar:2.8.1]

**Comment by GregSilverman** [comment] 2018-02-02 21:40
On another note, I was renaming these files to ._ from .txt, and they were still being read in. I am using the default Extension Glob, too. Should files with ._ as an extension then get skipped?

**Comment by GregSilverman** [comment] 2018-02-03 20:33
More on biomediucs error: Grepped the above files for non-printable ascii/control characters with null results. Not sure what else to check on these files and why they are throwing errors. NB: I did try setting the logging to debug/trace, but was unable to get more detail on the error being thrown.

A couple questions:
1. Would it be possible to modify the pipeline to instead of crashing when hitting this particular error that it would just log/flag the file as bad and continue processing (instead of terminating)?
2.  Is it possible to give more detail as to what is throwing the error?

These results confirm those discovered by @rfinz, with the addition of the particular files throwing the error.

**Comment by GregSilverman** [comment] 2018-02-05 03:11
Moved mimic data set specific errors  here #9.

**Comment by GregSilverman** [comment] 2018-02-05 03:23
@rmcewan, regarding use of isValidXmlFile, the mimic data are text files. Not sure how that would help. Please elaborate.

**Comment by GregSilverman** [comment] 2018-02-05 20:18
Got nlptab/nlptab-web up and spinning. Will create zip file with necessary XMI with TypeSystem of mimic data for testing (once we have the full workable data set defined).

**Comment by rmcewan** [comment] 2018-02-06 00:31
@GregSilverman You are correct - that will not do for text files. My bad.

**Comment by GregSilverman** [comment] 2018-02-06 21:01
Got nlptab, nlptab-web working:

- Need [ElasticSearch 2.1.0](https://www.elastic.co/blog/elasticsearch-2-1-0-and-2-0-1-released))
- Dependencies (MacOS):

```
brew install bower
sudo npm install gulp-cli -g
npm install gulp
sudo npm install browserify --save, npm install vinyl-source-stream --save
npm uninstall gulp-browserify --save
```
Need enable CORS on ElasticSearch (in config/elasticsearch.yml) :

```
http.cors.enabled: true
http.cors.allow-origin: '*'
```

**Comment by GregSilverman** [comment] 2018-02-08 22:27
@benknoll-umn, I just verified biomedicus build 1.8.4 now processes - after preprocessing (stripping off of non-printable ASCII and blank control characters) - the entire mimic data set through the CPE pipeline without error.

**Comment by GregSilverman** [comment] 2018-02-10 01:01
@rfinz, you will need to remove your shared data folder from the distribution:
<img width="390" alt="screen shot 2018-02-09 at 3 58 22 pm" src="https://user-images.githubusercontent.com/1007034/36056627-94c9d662-0dcb-11e8-9182-452782c8808d.png">
<img width="746" alt="screen shot 2018-02-09 at 3 55 43 pm" src="https://user-images.githubusercontent.com/1007034/36056628-94dff12c-0dcb-11e8-8ff2-713d4781fa27.png">

**Comment by GregSilverman** [comment] 2018-02-12 17:06
@rfinz, tested NLP-IE VM on following clean/untouched mimic data set:

10069.txt	
10283.txt	
10452.txt	
1221.txt	
1761.txt
10233.txt	
1044.txt	
1085.txt	
1439.txt	
1965.txt

All files pass without any issue on:

1. Ctakes
2. Biomedicus

Two files error on 

3. MetaMap 

10283.txt ->  due to two floating '.' 

1965.txt -> OutOfMemory Error (due to ill-formed fraction).

Removed 1965.txt and used clean 10283.txt (removed two stray '.') and reran all 3-annotator systems with success.

**Comment by GregSilverman** [comment] 2018-02-12 17:16
@rfinz, ran Amicus and got the following error (looks like a directory issue wrt the mimic file tree structure; NB: I had all files flattened in my data directory):

<img width="801" alt="screen shot 2018-02-12 at 11 14 19 am" src="https://user-images.githubusercontent.com/1007034/36109846-2d7efbd2-0fe6-11e8-9459-f44da0fe05e0.png">

**Comment by rfinz** [comment] 2018-02-12 17:28
@GregSilverman Ah yes, had to do that in order to test with the mimic data in its original hierarchy. I'll change it to its generic form.

**Comment by GregSilverman** [comment] 2018-02-12 17:30
@rfinz, I am currently marking up the NLP-IE VM instructions for usage. Please review and accept changes.

@rmcewan: some outstanding issues:

1. There is a type system definition for Clamp in NLP-Tab; should we hold off releasing this in NLP-Tab, at least until we get the Clamp licensing issue resolved that is holding up installation on the VM?

2. There is no type system defined for MetaMap in NLP-Tab. Setting up the zip files to create one is a non-trivial exercise. Do we need to add a how-to in the instructions?

**Comment by rfinz** [comment] 2018-02-13 19:46
Outstanding issues regard the VM Evolution and not the initial verification. Closing issue.

**Closed as completed by rfinz** 2018-02-13 19:46 UTC
